apiVersion: v1
kind: Service # 网络服务
metadata:
  name: svc-apigw
  namespace: go-micro # 都设置在一个命名空间下，相同网络
  labels:
    app: svc-apigw
spec:
  type: NodePort
  ports:
    - port: 8091 # cluster模式访问的端口
      nodePort: 30088   #设置 nodeport 端口 30000-32767 此时
                      # targetPort:访问容器内部的端口,与containerPort值相同。 当没有设置targetPort时,此时targetPort的值与port相同
  selector:
    app: svc-apigw